# Generated by Django 3.1.7 on 2021-04-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_auto_20210405_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='catid',
            field=models.IntegerField(default='0'),
        ),
    ]
