# Generated by Django 3.1.7 on 2021-04-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210403_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
