# Generated by Django 3.1.7 on 2021-05-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210331_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
