# Generated by Django 3.1.7 on 2021-05-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='utxt',
            field=models.TextField(default='-'),
        ),
    ]
